# This rule is not used by the project gitea-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to hyperspike.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gitea-operator
    app.kubernetes.io/managed-by: kustomize
  name: migraterepo-viewer-role
rules:
- apiGroups:
  - hyperspike.io
  resources:
  - migraterepoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hyperspike.io
  resources:
  - migraterepoes/status
  verbs:
  - get
