## Append samples of your project ##
resources:
- gitea.yaml
- org.yaml
- repo.yaml
- user.yaml
- v1_runner.yaml
- v1_auth.yaml
- v1_migraterepo.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
