apiVersion: hyperspike.io/v1
kind: Gitea
metadata:
  labels:
    app.kubernetes.io/name: gitea-operator
    app.kubernetes.io/managed-by: kustomize
  name: gitea
spec:
  postgres:
    provider: cnpg # or zalando (default)
  valkey: true
  # TODO(user): Add fields here
